### ISSUE TITLE
AFM Eval DB Preset change causes error

### ISSUE THREAD

**Issue by jvansan** [patrickbryant1/EvoBind#26]
Firstly, thank you for your rapid responses to these issue - you're help is invaluable.

I was looking to evaluate the difference in "performance" (both compute and prediction quality) when changing the AFM_eval from the `reduced_dbs` to `full_dbs` preset. At first this seemed as simple as  changing the parameter in the `src/AFM_eval/gen_AFM_feats.sh` script and making sure all the correct DB were specified. However, after all the HMM searches completed, I received the following error (with trace):

```
Traceback (most recent call last):
  File "/home/ubuntu/efs/evobind/src/AFM_eval/.//run_alphafold_msa_template_only.py", line 341, in <module>
    app.run(main)
  File "/home/ubuntu/miniconda3/envs/evobind/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/ubuntu/miniconda3/envs/evobind/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/ubuntu/efs/evobind/src/AFM_eval/.//run_alphafold_msa_template_only.py", line 318, in main
    get_features(
  File "/home/ubuntu/efs/evobind/src/AFM_eval/.//run_alphafold_msa_template_only.py", line 210, in get_features
    feature_dict = data_pipeline.process(
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/evobind/src/AFM_eval/alphafold/data/pipeline_multimer.py", line 267, in process
    chain_features = self._process_single_chain(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/evobind/src/AFM_eval/alphafold/data/pipeline_multimer.py", line 215, in _process_single_chain
    chain_features = self._monomer_data_pipeline.process(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/evobind/src/AFM_eval/alphafold/data/pipeline.py", line 245, in process
    msa_features = make_msa_features((uniref90_msa, bfd_msa, mgnify_msa))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/efs/evobind/src/AFM_eval/alphafold/data/pipeline.py", line 66, in make_msa_features
    for sequence_index, sequence in enumerate(msa.sequences):
                                              ^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'sequences'
```

I can cofirm that I was using the test inputs and that the script runs as intended with the `reduced_dbs` preset specified. 
This may be related to #24 as well.

Do you have any ideas on why this may be the case or what can be done to fix this problem?

**Comment by patrickbryant1** [comment]
Hi,

You need to rewrite that part of the code if you want to use other databases. We provide the MSA directly which is another alternative:
1. Generate all MSAs you want
2. Merge to a3m
3. Predict

Best,

Patrick

**Comment by kyleford8** [comment]
Looking over my previous issue, yes, I also was trying to run with full dbs.

**Comment by patrickbryant1** [comment]
Only the exact settings described are supported. If you want to change something you will have to make the necessary modifications yourself.
